// 54 sovereign African nations, alphabetical. Flag emojis for quick visual anchor.
export interface Country {
  name: string;
  code: string;
  flag: string;
}

export const AFRICAN_COUNTRIES: Country[] = [
  { name: "Algeria", code: "DZ", flag: "🇩🇿" },
  { name: "Angola", code: "AO", flag: "🇦🇴" },
  { name: "Benin", code: "BJ", flag: "🇧🇯" },
  { name: "Botswana", code: "BW", flag: "🇧🇼" },
  { name: "Burkina Faso", code: "BF", flag: "🇧🇫" },
  { name: "Burundi", code: "BI", flag: "🇧🇮" },
  { name: "Cabo Verde", code: "CV", flag: "🇨🇻" },
  { name: "Cameroon", code: "CM", flag: "🇨🇲" },
  { name: "Central African Republic", code: "CF", flag: "🇨🇫" },
  { name: "Chad", code: "TD", flag: "🇹🇩" },
  { name: "Comoros", code: "KM", flag: "🇰🇲" },
  { name: "Côte d'Ivoire", code: "CI", flag: "🇨🇮" },
  { name: "Democratic Republic of the Congo", code: "CD", flag: "🇨🇩" },
  { name: "Djibouti", code: "DJ", flag: "🇩🇯" },
  { name: "Egypt", code: "EG", flag: "🇪🇬" },
  { name: "Equatorial Guinea", code: "GQ", flag: "🇬🇶" },
  { name: "Eritrea", code: "ER", flag: "🇪🇷" },
  { name: "Eswatini", code: "SZ", flag: "🇸🇿" },
  { name: "Ethiopia", code: "ET", flag: "🇪🇹" },
  { name: "Gabon", code: "GA", flag: "🇬🇦" },
  { name: "Gambia", code: "GM", flag: "🇬🇲" },
  { name: "Ghana", code: "GH", flag: "🇬🇭" },
  { name: "Guinea", code: "GN", flag: "🇬🇳" },
  { name: "Guinea-Bissau", code: "GW", flag: "🇬🇼" },
  { name: "Kenya", code: "KE", flag: "🇰🇪" },
  { name: "Lesotho", code: "LS", flag: "🇱🇸" },
  { name: "Liberia", code: "LR", flag: "🇱🇷" },
  { name: "Libya", code: "LY", flag: "🇱🇾" },
  { name: "Madagascar", code: "MG", flag: "🇲🇬" },
  { name: "Malawi", code: "MW", flag: "🇲🇼" },
  { name: "Mali", code: "ML", flag: "🇲🇱" },
  { name: "Mauritania", code: "MR", flag: "🇲🇷" },
  { name: "Mauritius", code: "MU", flag: "🇲🇺" },
  { name: "Morocco", code: "MA", flag: "🇲🇦" },
  { name: "Mozambique", code: "MZ", flag: "🇲🇿" },
  { name: "Namibia", code: "NA", flag: "🇳🇦" },
  { name: "Niger", code: "NE", flag: "🇳🇪" },
  { name: "Nigeria", code: "NG", flag: "🇳🇬" },
  { name: "Republic of the Congo", code: "CG", flag: "🇨🇬" },
  { name: "Rwanda", code: "RW", flag: "🇷🇼" },
  { name: "São Tomé and Príncipe", code: "ST", flag: "🇸🇹" },
  { name: "Senegal", code: "SN", flag: "🇸🇳" },
  { name: "Seychelles", code: "SC", flag: "🇸🇨" },
  { name: "Sierra Leone", code: "SL", flag: "🇸🇱" },
  { name: "Somalia", code: "SO", flag: "🇸🇴" },
  { name: "South Africa", code: "ZA", flag: "🇿🇦" },
  { name: "South Sudan", code: "SS", flag: "🇸🇸" },
  { name: "Sudan", code: "SD", flag: "🇸🇩" },
  { name: "Tanzania", code: "TZ", flag: "🇹🇿" },
  { name: "Togo", code: "TG", flag: "🇹🇬" },
  { name: "Tunisia", code: "TN", flag: "🇹🇳" },
  { name: "Uganda", code: "UG", flag: "🇺🇬" },
  { name: "Zambia", code: "ZM", flag: "🇿🇲" },
  { name: "Zimbabwe", code: "ZW", flag: "🇿🇼" },
];
